### ISSUE TITLE
Traduction de la documentation officielle de Ren'Py

### ISSUE THREAD

**Issue by GoulvenC** [gamedevalliance/wiki#83]
## Traduction documentation Ren'Py

L'objectif étant de permettre aux débutants et aux utilisateurs intermédiaires de découvrir le moteur Ren'Py grâce à une documentation en Francais, sur notre Wiki moderne. La priorité est donc de traduire les pages de la documentation destinés aux débutants et aux utilisateurs intermédiaires, mais la documentation avancée peut également être traduite. 
N'hésitez pas à reformuler ou à corriger des erreurs que vous pouvez trouver, l'objectif est d'obtenir une documentation utile et agréable plus qu'une copie conforme de la documentation en Anglais.
Également il serait cool de suivre les mises à jours que ce soit du moteur ou de la documentation officielle, afin de garder notre documentation à jour (contrairement aux tutoriels de 2013 que l'on trouve sur google)
Enfin, n’hésitez pas à diviser un chapitre en plusieurs partie afin de ne pas se fatiguer inutilement. 

### Objectifs
- **Débuter dans Ren'Py :** Normalement c'est bon, à voir si vous souhaitez rajouter des trucs
- **Progresser dans Ren'Py :** Finir de traduire "Customiser l'apparence de votre" ( PR #84 , Nev est dessus )
- **Progresser dans Ren'Py :** A la suite de "Comprendre le langage Ren'Py (Pr #96 ) continuer avec 3 articles qui serait "Labels et dialogues" (Traduction de "Labels & control flow" + "Dialogue and Narration") , un article "Images et menu" (Traduction de "Displaying images" + "In Game Menus" ) et un article "Audio, vidéo et voix" (Traduction de "Audio" + "Movie" + "Voice" )

### Parties à traduire
- [x] Quickstart (PR #75 #76 #77 #79 )
- [ ] GUI Customization Guide
    - [x] Simple GUI Customization (PR #82 )
    - [ ] Intermediate GUI Customization
    - [x] Advanced Customization (PR #84 )
- [ ] The Ren'Py Language
   - [x] Language basics (PR #96 )
   - [ ] Labels & Control Flow
   - [ ] Dialogue and Narration
   - [x] Displaying Images
   - [x] In-Game Menus
   - [ ] Python Statements
   - [ ] Conditional Statements
   - [ ] Audio
   - [ ] Movie
   - [ ] Voice
- [ ] Text, Displayables, Transforms, and Transitions 
- [ ] Customizing Ren'Py
- [ ] Tools
- [ ] Other Functionality 
- [ ] Building, Updating, and Other Platforms
- [ ] End-User Documentation
- [ ] Engine Developer Documentation
- [ ] Changes, License, and Credits
- [ ] Indices
- [ ] Example Scripts

### Liens utiles

- [La documentation officielle](https://www.renpy.org/doc/html/)
- [Le portail Ren'Py](https://wiki.rpgmakeralliance.com/renpy)

**Comment by GoulvenC** [comment]
Modification des plans. On annule la traduction. Voir page du projet : https://github.com/gamedevalliance/wiki/projects/1
